# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fbc2aede1e869945d11ba5bad1be17dd77643fabc5aa6e2156087969f0c9df23fddd4c20de347bcdb1d41a9f0d5d5e39909c1cf28377da705da54d64f818b93

test:
  secret_key_base: 5dd1f738f25139105cdf918976841962e4316e57247f66b7cbfdb02bc516ccd4babedc922b5acd5efbbed47c4fb57b49b88a0c31c854d3a82a363057578159c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
